# tasks.py

tasks = [
    "Can you help me stay focused on my reading for the next 10 minutes?",
    "What is the best way to break down a complex task into smaller steps?",
    "Can you remind me about my meeting in 30 minutes?",
    "How should I organize my work schedule for the week?",
    "What should I do if I feel overwhelmed by all the tasks I need to do?",
    "Can you help me organize my to-do list for the day?",
    "How can I improve my focus when I'm feeling distracted?",
    "Can you remind me about my homework assignment?",
    "How do I stop procrastinating and start working on my tasks?",
    "Can you give me some tips for staying motivated to finish my project?",
    "What are some ways to manage my anxiety when I feel overwhelmed?",
    "Can you help me set reminders for my daily tasks?",
    "How do I avoid distractions when I'm studying?",
    "Can you suggest ways to stay focused during work?",
    "What should I do if I forget something important?",
    "Can you help me plan my day more effectively?",
    "How do I organize my notes for school?",
    "Can you give me a step-by-step plan for completing my homework?",
    "What are some tips to help me remember important dates or events?",
    "Can you give me a pep talk to get me motivated to study?",
    "I have a big presentation tomorrow, and I’m feeling so scatterbrained. Can you help me outline my key talking points and rehearse effectively?",
    "I’m overloaded with house chores, and I keep forgetting small tasks like taking out the trash or doing laundry. How can I organize these tasks so I don’t miss anything?",
    "I’m supposed to study for a science quiz tonight, but I can’t stop scrolling on social media. Can you help me create a distraction-free study routine?",
    "My boss emailed me about an important project deadline in two days, but I’m freaking out because I haven’t started. What’s a good strategy to catch up quickly?",
    "I’ve promised to meet friends this weekend, but I also have to finish my homework. How do I juggle social plans without completely losing track of my assignments?",
    "I need to prepare dinner for guests tonight, but I’m overwhelmed deciding what to cook and how to manage the timing. Can you help me plan step-by-step?",
    "I’ve been asked to join a new extracurricular activity at school, but I’m worried I won’t manage my existing responsibilities. How can I schedule everything without burning out?",
    "I’m moving next week and have so many boxes to pack, but I can’t seem to start. Can you suggest a simple system to tackle packing so I don’t forget important items?",
    "I have multiple bills to pay this month, and I’m worried I’ll miss due dates. Can you help me create a payment schedule and reminders?",
    "My teacher just assigned a group project, and I don’t want to let my teammates down. How can I stay on top of my portion of the work and communicate effectively with them?"
]
